<?php

/**
 * @file
 * Provides a dedicated 'Mercury Editor' task (tab) to the editing experience.
 */

declare(strict_types=1);

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;

/**
 * Implements hook_menu_local_tasks_alter().
 */
function mercury_editor_task_menu_local_tasks_alter(array &$data, string $route_name, RefinableCacheableDependencyInterface &$cacheability): void {
  // Must alter the task label when it is rendered (not discovered) so that
  // we can use the translated configuration label.
  $link =& NestedArray::getValue($data, ['tabs', 0, 'entity.node.mercury_editor_task', '#link']);
  if ($link) {
    // Set label.
    $link['title'] = \Drupal::config('mercury_editor_task.settings')->get('label');
    // Add languages to cache contexts.
    $cacheability->addCacheContexts(['languages']);
  }
}

/**
 * Implements hook_task_entity_operation_alter().
 */
function mercury_editor_task_entity_operation_alter(array &$operations, EntityInterface $entity): void {
  // Add 'Mercury Editor' to operations when node type supports 'Mercury Editor'.
  $entity_type_id = $entity->getEntityTypeId();
  $bundle = $entity->bundle();
  if ($entity instanceof NodeInterface
    && $entity->access('update')
    && !empty(\Drupal::config('mercury_editor.settings')->get("bundles.$entity_type_id.$bundle"))) {
    $operations['mercury_editor_task'] = [
      'title' => \Drupal::config('mercury_editor_task.settings')->get('label'),
      'url' => Url::fromRoute('entity.node.mercury_editor_task', ['node' => $entity->id()]),
      'weight' => 11,
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds submission handler for Mercury Editor Settings form.
 *
 * @see _mercury_editor_task_form_mercury_editor_settings_form_submit()
 * @see \Drupal\mercury_editor\Form\SettingsForm
 */
function mercury_editor_task_form_mercury_editor_settings_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $form['#submit'][] = '_mercury_editor_task_form_mercury_editor_settings_form_submit';
}

/**
 * Form submission handler for Mercury Editor Settings form.
 *
 * @see mercury_editor_task_form_mercury_editor_settings_form_alter()
 * @see \Drupal\mercury_editor\Form\SettingsForm
 */
function _mercury_editor_task_form_mercury_editor_settings_form_submit(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\mercury_editor_task\MercuryEditorTaskFormDisplayBuilderInterface $form_display_builder */
  $form_display_builder = \Drupal::service('mercury_editor_task.form_display_builder');

  $updated = $form_display_builder->updateContentTypes();
  if ($updated) {
    \Drupal::messenger()->addStatus(t('Mercury Editor form modes have been updated.'));
  }

  /** @var \Drupal\Core\Cache\CacheTagsInvalidatorInterface $cache_tags_invalidator */
  $cache_tags_invalidator = \Drupal::service('cache_tags.invalidator');
  $cache_tags_invalidator->invalidateTags(['local_task']);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function mercury_editor_task_form_node_form_alter(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\mercury_editor_task\MercuryEditorTaskFormAlterInterface $form_alter_service */
  $form_alter_service = \Drupal::service('mercury_editor_task.form_alter');
  $form_alter_service->formAlter($form, $form_state);
}

/**
 * Implements hook_preprocess_inline_entity_form_entity_table().
 */
function mercury_editor_task_preprocess_inline_entity_form_entity_table(array &$variables): void {
  if (empty($variables['table'])) {
    return;
  }
  /** @var \Drupal\mercury_editor_task\MercuryEditorTasksInlineEntityFormInterface $inline_entity_form */
  $inline_entity_form = \Drupal::service('mercury_editor_task.inline_entity_form');
  $inline_entity_form->addMercuryEditorLinks($variables['table']);
}
